- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: aryanrastogi
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "aryan7767/scientific-calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Stop existing container (if running)
      shell: docker rm -f calculator-container || true
    - name: Running container
      shell:  docker run -d --name calculator-container -p 2222:22 aryan7767/scientific-calculator:latest
