- name: Deploy Scientific Calculator Container
  hosts: all
  become: yes 
  vars:
    ansible_python_interpreter: /Users/aryanrastogi/.ansible-env/bin/python3

  tasks:
    - name: Install required Ansible collections
      ansible.builtin.command: ansible-galaxy collection install community.docker

    - name: Pull the latest Docker image
      community.docker.docker_image:
        name: "aryan7767/scientific-calculator"
        source: pull

    - name: Remove existing container (if running)
      community.docker.docker_container:
        name: calculator-container
        state: absent

    - name: Run the container
      community.docker.docker_container:
        name: calculator-container
        image: "aryan7767/scientific-calculator:latest"
        state: started
        restart_policy: always
        ports:
          - "8000:8000" 
