# - name: Pull Docker Image from Docker Hub
#   hosts: localhost
#   remote_user: aryanrastogi
#   become: false
#   vars:
#     ansible_python_interpreter: /usr/bin/python3.12
#   tasks:
#     - name: Pull Docker Image
#       docker_image:
#         name: "aryan7767/scientific-calculator"
#         source: pull
#       register: docker_pull_result

#     - name: Display Docker Pull Result
#       debug:
#         var: docker_pull_result
        
#     - name: Start Docker service
#       service:
#         name: docker
#         state: started
#     - name: Stop existing container (if running)
#       shell: docker rm -f calculator-container || true
#     - name: Running container
#       shell:  docker run -d --name calculator-container -p 2222:22 aryan7767/scientific-calculator:latest


- name: Deploy Scientific Calculator Container
  hosts: localhost
  remote_user: aryanrastogi
  become: true  # Required for managing Docker

  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  tasks:
    - name: Ensure Homebrew is installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

    - name: Install Homebrew (if missing)
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not homebrew_check.stat.exists

    - name: Install required Python packages using Homebrew
      homebrew:
        name:
          - python@3.12
          - docker
        state: present

    - name: Ensure Python packages are installed inside a virtual environment
      shell: |
        python3 -m venv ~/venv
        source ~/venv/bin/activate
        pip install docker requests
      args:
        executable: /bin/bash

    - name: Ensure Docker service is running
      shell: open -a Docker
      ignore_errors: yes  # Ignore if Docker is already running

    - name: Wait for Docker to be available
      command: docker info
      register: docker_status
      until: docker_status.rc == 0
      retries: 10
      delay: 5

    - name: Pull Docker Image from Docker Hub
      community.docker.docker_image:
        name: "aryan7767/scientific-calculator"
        source: pull

    - name: Remove existing container (if running)
      community.docker.docker_container:
        name: calculator-container
        state: absent  # Ensures old container is removed

    - name: Run the container
      community.docker.docker_container:
        name: calculator-container
        image: "aryan7767/scientific-calculator:latest"
        state: started
        restart_policy: always
        ports:
          - "2222:22"

