- hosts: remote_server
  tasks:
    - name: Pull latest Docker image
      shell: docker pull your-dockerhub/scientific-calculator

    - name: Stop existing container
      shell: docker rm -f calculator-container || true

    - name: Run new container
      shell: docker run -d --name calculator-container your-dockerhub/scientific-calculator
